Repository twosigma/marbles, pull requests merged in 2018-06, with the labels that each got.

#66 Include text files from metapackage in subpackage sdists
  MANIFEST.in
  docs/changelog.rst
  marbles/core/MANIFEST.in
  marbles/core/README.rst
  marbles/core/classifiers.txt
  marbles/core/setup.py
  marbles/mixins/MANIFEST.in
  marbles/mixins/README.rst
  marbles/mixins/classifiers.txt
  marbles/mixins/setup.py
Labels: bug, releng

#67 created tox shorthand for building and uploading packages to pypi
  docs/maintaining.rst
  tox.ini
Labels: releng

#68 integrate codecov
  .travis.yml
  README.rst
Labels: tests

#76 Pytest comparison edits
  docs/comparisons.rst
Labels: docs

#60 added comparison with pytest
  docs/comparisons.rst
  docs/index.rst
Labels: docs

#82 Forward environment variables to subprocess test runs
  marbles/core/tests/test_main.py
Labels: bug
